---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 55-gvt-gpu
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
    config:
      ignition:
        version: 3.1.0
      storage:
        files:
          - contents:
              source: >-
                data:text/plain;charset=utf-8;base64,b3B0aW9ucyBpOTE1IGVuYWJsZV9ndnQ9MQo=
            mode: 0644
            overwrite: true
            path: /etc/modprobe.d/gpu-intel.conf
          - contents:
              source: 'data:,kvmgt'
            mode: 0644
            overwrite: true
            path: /etc/modules-load.d/gpu-kvmgt.conf
      systemd:
        units:
          - contents: |
              [Unit]
              Description=Create Intel GVT-g vGPU

              [Service]
              Type=oneshot
              ExecStart=/bin/sh -c "echo '56a4c4e2-c81f-4cba-82bf-af46c30ea32d' > /sys/devices/pci0000:00/0000:00:02.0/mdev_supported_types/i915-GVTg_V5_8/create"
              ExecStart=/bin/sh -c "echo '973069b7-2025-406b-b3c9-301016af3150' > /sys/devices/pci0000:00/0000:00:02.0/mdev_supported_types/i915-GVTg_V5_8/create"
              ExecStop=/bin/sh -c "echo '1' > /sys/devices/pci0000:00/0000:00:02.0/56a4c4e2-c81f-4cba-82bf-af46c30ea32d/remove"
              ExecStop=/bin/sh -c "echo '1' > /sys/devices/pci0000:00/0000:00:02.0/973069b7-2025-406b-b3c9-301016af3150/remove"
              RemainAfterExit=yes

              [Install]
              WantedBy=multi-user.target
            enabled: true
            name: intelgvtg.service
    kernelArguments:
      - 'intel_iommu=on'