---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 56-xhci-unload
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
    config:
      ignition:
        version: 3.1.0
      systemd:
        units:
          - contents: |
              [Unit]
              Description=Unload XHCI driver from RTX8000 Cards to enable vfio driver:wq

              [Service]
              Type=oneshot
              ExecStart=/bin/bash /var/lib/nvconf/xhciunload.sh
              RemainAfterExit=yes

              [Install]
              WantedBy=multi-user.target
            enabled: true
            name: xhci-unload.service
      storage:
        files:
          - contents:
              source: >-
                data:text/plain;charset=utf-8;base64,IyEvYmluL2Jhc2gKSURTPWBsc3BjaSAtbm4gLWQgMTBkZToxYWQ2IHwgY3V0IC1mMSAtZCAnICdgCmlmIFsgISAteiAiJElEUyIgXQp0aGVuCiAgICBmb3IgaWQgaW4gJElEUzoKICAgIGRvCiAgICAgICAgZWNobyAtbiAwMDAwOiR7aWR9ID4gL3N5cy9idXMvcGNpL2RyaXZlcnMveGhjaV9oY2QvdW5iaW5kCiAgICAgICAgZWNobyAtbiAwMDAwOiR7aWR9ID4gL3N5cy9idXMvcGNpL2RyaXZlcnMvdmZpby1wY2kvYmluZAogICAgZG9uZQpmaQ==
            mode: 0755
            overwrite: true
            path: /var/lib/nvconf/xhciunload.sh